# Generated by Django 5.2.13 on 2026-04-13 18:52

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=apps.documents.models.document_upload_path),
        ),
    ]
