# Generated by Django 5.2.13 on 2026-04-28 09:42

import apps.documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=500, upload_to=apps.documents.models.document_upload_path),
        ),
    ]
